version: "2"
  
services:
  m2_reverse_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: proxy-net
